# /.github/workflows/daily.yml
# based on https://github.com/carbonphyber/watch-epa-superfund-sites/blob/main/.github/workflows/daily.yml
on:
  schedule:
    - cron:  '*/10 * * * *' # Every 10 minutes
name: Pull Data and Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Scrape
      run: |
        curl -o data/chp-incidents-raw.xml --no-progress-meter "https://media.chp.ca.gov/sa_xml/sa.xml?ts=$(date +%s)"
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
